<div class="mt-1">
    @switch($user_office->office_id)
        @case(1)
            <span>Registrar</span>
            @break
        @case(2)
            <span>VPAA</span>
            @break
        @case(3)
            <span>ICS</span>
            @break
        @case(4)
            <span>IBFS</span>
            @break
        @case(5)
            <span>ITE</span>
            @break
        @case(6)
            <span>IAS</span>
            @break
        @case(7)
            <span>IHS</span>
            @break
        @case(8)
            <span>ICJE</span>
            @break
    @endswitch
</div>